//+------------------------------------------------------------------+
//|                                              XAUUSD_D1_3.mq5
//| Generated by edge_research pipeline
//| Edge ID: XAUUSD_D1_3
//| Hypothesis: Price rally after rsi_7 < 35.0
//+------------------------------------------------------------------+
#property copyright "edge_research"
#property link      "https://github.com/your-org/edge-research"
#property version   "1.00"
#property strict
#property description "Auto-generated edge EA from edge_research"

#include <Trade\Trade.mqh>

//--- Input parameters (tunable)
input int          MAGIC_NUMBER      = 713211;        // Order magic
input double       LOT_SIZE          = 0.1;                   // Position size
input int          EXIT_BARS         = 1;           // Exit horizon
input double       VIRTUAL_SL_PIPS   = 20.0;                  // SL in pips
input double       VIRTUAL_TP_PIPS   = 30.0;                  // TP in pips
input bool         ENABLE_CSV_LOG    = true;                  // Log to CSV

//--- Global variables
CTrade            trade;
string            csv_filename;
int               last_entry_bar = -1;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit() {
    trade.SetExpertMagicNumber(MAGIC_NUMBER);
    
    csv_filename = "edge_" + Symbol() + "_" + TimeframeToString(Period()) + ".csv";
    
    if (ENABLE_CSV_LOG) {
        int csv_handle = FileOpen(csv_filename, FILE_WRITE | FILE_CSV | FILE_ANSI);
        if (csv_handle != INVALID_HANDLE) {
            FileWrite(csv_handle, "entry_time,entry_price,exit_time,exit_price,pnl_pips,result");
            FileClose(csv_handle);
        }
    }
    
    return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick() {
    // Close existing position if exit bars reached
    if (PositionSelectByMagic(MAGIC_NUMBER)) {
        int bars_held = (int)Bars(Symbol(), Period()) - PositionOpenBar(PositionGetTicket(0));
        if (bars_held >= EXIT_BARS) {
            trade.PositionClose(PositionGetTicket(0));
            LogTrade(PositionGetOpenPrice(), Bid, true);
        }
        return;
    }
    
    // Entry condition: check if signal fires
    if (last_entry_bar != Bars(Symbol(), Period()) && CheckEntryCondition()) {
        double entry_price = Ask;
        double stop_loss = entry_price - VIRTUAL_SL_PIPS * Point();
        double take_profit = entry_price + VIRTUAL_TP_PIPS * Point();
        
        trade.Buy(LOT_SIZE, Symbol(), entry_price, stop_loss, take_profit, "edge");
        
        last_entry_bar = Bars(Symbol(), Period());
    }
}

//+------------------------------------------------------------------+
//| Check entry condition                                            |
//+------------------------------------------------------------------+
bool CheckEntryCondition() {
    // Compiled entry condition from edge_research
    rsi_7 < 35.0
}

//+------------------------------------------------------------------+
//| Get indicator value (wrapper for safety)                         |
//+------------------------------------------------------------------+
double GetIndicatorValue(int handle, int bar_index) {
    double buffer[1];
    if (CopyBuffer(handle, 0, bar_index, 1, buffer) <= 0) {
        return 0.0;
    }
    return buffer[0];
}

//+------------------------------------------------------------------+
//| Log trade result to CSV                                          |
//+------------------------------------------------------------------+
void LogTrade(double entry_price, double exit_price, bool success) {
    if (!ENABLE_CSV_LOG) return;
    
    int csv_handle = FileOpen(csv_filename, FILE_READ | FILE_WRITE | FILE_CSV | FILE_ANSI);
    if (csv_handle == INVALID_HANDLE) return;
    
    FileSeek(csv_handle, 0, SEEK_END);
    
    double pnl_pips = (exit_price - entry_price) / Point();
    string result = (pnl_pips > 0) ? "WIN" : "LOSS";
    
    FileWrite(
        csv_handle,
        TimeToString(TimeCurrent(), TIME_DATE | TIME_MINUTES),
        DoubleToString(entry_price, Digits),
        TimeToString(TimeCurrent(), TIME_DATE | TIME_MINUTES),
        DoubleToString(exit_price, Digits),
        DoubleToString(pnl_pips, 1),
        result
    );
    
    FileClose(csv_handle);
}

//+------------------------------------------------------------------+
//| Timeframe to string                                              |
//+------------------------------------------------------------------+
string TimeframeToString(ENUM_TIMEFRAMES tf) {
    switch(tf) {
        case PERIOD_M1:  return "M1";
        case PERIOD_M5:  return "M5";
        case PERIOD_M15: return "M15";
        case PERIOD_M30: return "M30";
        case PERIOD_H1:  return "H1";
        case PERIOD_H4:  return "H4";
        case PERIOD_D1:  return "D1";
        default: return "UNKNOWN";
    }
}

//+------------------------------------------------------------------+
//| Position helper functions                                         |
//+------------------------------------------------------------------+
bool PositionSelectByMagic(int magic) {
    for (int i = PositionsTotal() - 1; i >= 0; i--) {
        if (PositionGetTicket(i) > 0 && PositionGetInteger(POSITION_MAGIC) == magic) {
            return true;
        }
    }
    return false;
}

int PositionOpenBar(ulong ticket) {
    if (PositionSelectByTicket(ticket)) {
        return (int)Bars(Symbol(), Period()) - (int)BarShift(Symbol(), Period(), PositionGetInteger(POSITION_TIME));
    }
    return 0;
}
